# Generated by Django 5.0.6 on 2024-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
