# Generated by Django 5.0.6 on 2024-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
